---
name: Linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  lint:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Super-Linter
      uses: github/super-linter@v4.9.4
      env:
        GITHUB_TOKEN: {{ secrets.GITHUB_TOKEN }}
        FILTER_REGEX_EXCLUDE: ".*(Fantasy Adventure Environment|TextMesh Pro|SineVFX).*"
